Repository decred/dcrdata, pull requests merged in 2018-07, with the labels that each got.

#529 stakedb: fix loading bug in ticket pool db
  stakedb/ticketpool.go
Labels: critical-fix

#528 dcrpg: fix empty prev_hash in block_chain
  db/dcrpg/internal/blockstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/queries.go
Labels: bug

#527 stakedb: recovery and robustness with upserts
  cmd/rebuilddb2/rebuilddb2.go
  db/dcrpg/insightapi.go
  db/dcrpg/internal/addrstmts.go
  db/dcrpg/internal/stakestmts.go
  db/dcrpg/internal/vinoutstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/queries.go
  db/dcrsqlite/apisource.go
  db/dcrsqlite/sync.go
  stakedb/stakedb.go
  stakedb/ticketpool.go
  stakedb/ticketpool_test.go
Labels: enhancement, needs testing

#463 Add charts
  api/apirouter.go
  api/apiroutes.go
  cmd/rebuilddb2/rebuilddb2.go
  db/dbtypes/extraction.go
  db/dbtypes/types.go
  db/dcrpg/internal/blockstmts.go
  db/dcrpg/internal/stakestmts.go
  db/dcrpg/internal/txstmts.go
  db/dcrpg/internal/vinoutstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/queries.go
  db/dcrpg/tables.go
  db/dcrpg/upgrades.go
  db/dcrsqlite/apisource.go
  db/dcrsqlite/sqlite.go
  explorer/explorer.go
  explorer/explorerroutes.go
  explorer/explorertypes.go
  main.go
  middleware/apimiddleware.go
  public/css/charts.css
  public/images/loader.gif
  public/js/controllers/charts.js
  public/js/dygraphs.min.js
  public/js/plotly.min.js
  views/charts.tmpl
  views/extras.tmpl
Labels: enhancement

#524 Consolidated debit view
  api/insight/apiroutes.go
  db/dbtypes/types.go
  db/dcrpg/insightapi.go
  db/dcrpg/internal/addrstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/queries.go
  explorer/explorerroutes.go
  explorer/explorertypes.go
  views/address.tmpl
Labels: needs testing

#552 dcrpg: start proper side chain handling, upgrades
  cmd/rebuilddb2/rebuilddb2.go
  db/dbtypes/extraction.go
  db/dbtypes/types.go
  db/dcrpg/internal/addrstmts.go
  db/dcrpg/internal/blockstmts.go
  db/dcrpg/internal/stakestmts.go
  db/dcrpg/internal/txstmts.go
  db/dcrpg/internal/vinoutstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/queries.go
  db/dcrpg/sync.go
  db/dcrpg/tables.go
  db/dcrpg/upgrades.go
  explorer/explorertypes.go
Labels: ready to go
