Repository decred/dcrdata, pull requests merged in 2018-10, with the labels that each got.

#714 'confirms' formatting on websocket update in views/transaction
  views/extras.tmpl
  views/tx.tmpl
Labels: needs testing

#710 Load webserver soonest possible
  README.md
  cmd/rebuilddb/rebuilddb.go
  cmd/rebuilddb2/rebuilddb2.go
  config.go
  db/dbtypes/types.go
  db/dcrpg/indexing.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/sync.go
  db/dcrpg/tables.go
  db/dcrsqlite/apisource.go
  db/dcrsqlite/sync.go
  explorer/explorer.go
  explorer/explorermiddleware.go
  explorer/explorerroutes.go
  explorer/explorertypes.go
  explorer/websocket.go
  explorer/websockethandlers.go
  main.go
  public/css/main.css
  public/js/controllers/status.js
  sample-dcrdata.conf
  views/extras.tmpl
  views/nexthome.tmpl
  views/status.tmpl
Labels: ready to go

#720 fix stakedb rewind error on startup
  config.go
  db/dcrpg/sync.go
  db/dcrsqlite/apisource.go
  db/dcrsqlite/sync.go
  main.go
Labels: bug

#722 Display indexing subtitle notification before it starts
  db/dcrpg/indexing.go
Labels: bug-fix

#717 Full side chain import from dcrd on startup
  api/types/apitypes.go
  blockdata/blockdata.go
  blockdata/datasaver.go
  cmd/scanblocks/scanblocks.go
  db/dbtypes/types.go
  db/dcrpg/insightapi.go
  db/dcrpg/pgblockchain.go
  db/dcrsqlite/apisource.go
  db/dcrsqlite/sqlite.go
  db/dcrsqlite/sync.go
  explorer/explorer.go
  main.go
  mempool/mempool.go
  rpcutils/rpcclient.go
  rpcutils/rpcclient_online_test.go
  rpcutils/rpcclient_test.go
Labels: enhancement, needs review

#726 Register for dcrd notifications before waiting for monitors to exit
  main.go
Labels: bug-fix

#731 dcrpg: fix panic while importing side chain block with missed vote
  db/dcrpg/queries.go
Labels: bug-fix

#729 dcrsqlite: properly compute blocks to check in sync
  db/dcrsqlite/sync.go
Labels: bug-fix

#736 config: adjust config/log/data paths if appdata is changed
  api/apiroutes.go
  config.go
  config_test.go
  main.go
Labels: bug-fix, needs testing

#740 config: restore env tags in config struct
  README.md
  config.go
Labels: bug-fix

#738 Sync fixes
  db/dcrsqlite/sqlite.go
  db/dcrsqlite/sync.go
  main.go
Labels: bug-fix

#751 dcrpg: major optimization with pool status update
  db/dcrpg/internal/blockstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/queries.go
  explorer/explorer.go
Labels: enhancement, needs review, needs testing

#745 side chain import fixes and block sync/store refactoring
  api/apiroutes.go
  cmd/rebuilddb2/rebuilddb2.go
  db/dcrpg/chainmonitor.go
  db/dcrpg/internal/addrstmts.go
  db/dcrpg/internal/blockstmts.go
  db/dcrpg/internal/stakestmts.go
  db/dcrpg/internal/txstmts.go
  db/dcrpg/internal/vinoutstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/queries.go
  db/dcrpg/sync.go
  db/dcrsqlite/apisource.go
  explorer/explorer.go
  explorer/explorerroutes.go
  explorer/explorertypes.go
  explorer/mempool.go
  main.go
  rpcutils/rpcclient.go
  stakedb/stakedb.go
Labels: bug-fix, needs testing

#760 fix chart zoom for uninitialized charts
  public/js/controllers/address.js
Labels: bug-fix

#770 Fix bugs in 3.0 version
  db/dcrpg/internal/addrstmts.go
  db/dcrpg/internal/stakestmts.go
  public/css/nexthome.css
  public/images/logo-2018.svg
  public/images/themes/light/logo.svg
  public/images/themes/night/logo.svg
  public/js/controllers/address.js
  public/js/controllers/agenda.js
  views/agenda.tmpl
  views/extras.tmpl
Labels: bug-fix

#775 Mempool spending txs checked against confirmed txs on address page
  explorer/explorerroutes.go
Labels: bug-fix
