Repository decred/dcrdata, pull requests merged in 2018-02, with the labels that each got.

#341 fixing the search for addresses with no transactions
  db/dcrsqlite/apisource.go
  explorer/explorerroutes.go
  explorer/explorertypes.go
  views/address.tmpl
Labels: needs testing

#337 improve fresh start error handling and logging
  db/dcrsqlite/apisource.go
  db/dcrsqlite/sqlite.go
  db/dcrsqlite/sync.go
  stakedb/stakedb.go
Labels: needs review, needs testing

#311 Desktop Notifications
  public/images/dcrdata.min.svg
  public/images/dcrdata.svg
  public/images/dcrdata144x128.png
  public/js/notify.js
  public/js/notify.min.js
  version.go
  views/extras.tmpl
Labels: ready to go

#300 Stake tables: tickets, votes, misses
  .gitignore
  Gopkg.lock
  README.md
  blockdata/blockdata.go
  cmd/rebuilddb2/.gitignore
  cmd/rebuilddb2/config.go
  cmd/rebuilddb2/rebuilddb2.go
  db/dbtypes/types.go
  db/dcrpg/internal/addrstmts.go
  db/dcrpg/internal/blockstmts.go
  db/dcrpg/internal/common.go
  db/dcrpg/internal/stakestmts.go
  db/dcrpg/internal/txstmts.go
  db/dcrpg/internal/vinoutstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/pgblockchain_test.go
  db/dcrpg/queries.go
  db/dcrpg/sync.go
  db/dcrpg/tables.go
  db/dcrsqlite/apisource.go
  db/dcrsqlite/sqlite.go
  db/dcrsqlite/sync.go
  dcrdataapi/apitypes.go
  explorer/explorer.go
  explorer/explorerroutes.go
  explorer/explorertypes.go
  main.go
  mempool/mempool.go
  stakedb/stakedb.go
  version.go
  views/block.tmpl
  views/tx.tmpl
Labels: ready to go

#354 synchronize startup scan for all DBs
  apimiddleware.go
  blockdata/blockdata.go
  cmd/rebuilddb/rebuilddb.go
  cmd/scanblocks/log.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/queries.go
  db/dcrpg/sync.go
  db/dcrpg/tables.go
  db/dcrsqlite/apisource.go
  db/dcrsqlite/sync.go
  dev/wipedbs.sh
  explorer/explorer.go
  explorer/websocket.go
  main.go
  ntfnhandlers.go
  rpcutils/blockgate.go
  rpcutils/rpcclient.go
  semver/semver.go
  stakedb/stakedb.go
  txhelpers/txhelpers.go
Labels: needs review, needs testing
