Repository decred/dcrdata, pull requests merged in 2018-03, with the labels that each got.

#386 explorer/websocket: avoid repeatedly unregistering a websocket client
  explorer/websockethandlers.go
Labels: bug

#394 do not request previous vout extra data when just counting transactions
  db/dcrsqlite/apisource.go
Labels: bug

#391 main: prevent hang after reindex
  main.go
Labels: bug

#395 explorer: refactor the explorer templates so they are easier to manage
  explorer/explorer.go
  explorer/explorermiddleware.go
  explorer/explorerroutes.go
  explorer/templates.go
Labels: enhancement

#402 insight: rawblock endpoint
  api/apiroutes.go
  api/insight/apimiddleware.go
  api/insight/apirouter.go
  api/insight/apiroutes.go
  db/dcrpg/insightapi.go
  middleware/apimiddleware.go
Labels: insight API

#413 explorer/websocket: fix insane ping loop that was in websocket handler
  explorer/websocket.go
  explorer/websockethandlers.go
Labels: critical-fix

#415 explorer: avoid concurrent map access
  explorer/websocket.go
  explorer/websockethandlers.go
Labels: critical-fix
