Repository decred/dcrdata, pull requests merged in 2018-08, with the labels that each got.

#563 dcrsqlite: test RetrieveAllPoolValAndSize and RetrieveBlockFeeInfo, tier 3
  .gitignore
  Gopkg.lock
  db/dcrsqlite/blocksretrieval_test.go
  db/dcrsqlite/dcrsqlite_test.go
Labels: tests

#562 dcrsqlite: test GetBestBlockHash, GetBestBlockHeight, GetStakeInfoHeight, tier 2
  db/dcrsqlite/blocksretrieval_test.go
Labels: tests

#580 dcrpg: reorg handling
  blockdata/chainmonitor.go
  db/dcrpg/chainmonitor.go
  db/dcrpg/insightapi.go
  db/dcrpg/internal/addrstmts.go
  db/dcrpg/internal/blockstmts.go
  db/dcrpg/internal/stakestmts.go
  db/dcrpg/internal/txstmts.go
  db/dcrpg/internal/vinoutstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/queries.go
  db/dcrpg/tables.go
  db/dcrpg/upgrades.go
  db/dcrsqlite/apisource.go
  main.go
  notification/ntfnchans.go
  notification/ntfnhandlers.go
  stakedb/stakedb.go
Labels: needs review, needs testing

#630 dcrpg: fix upgrade to 3.5.1 from <3.5.0
  db/dcrpg/upgrades.go
Labels: critical-fix
