Repository decred/dcrdata, pull requests merged in 2018-12, with the labels that each got.

#859 [3.1] prePopulateChartsData was blocking explorerUI.Store
  explorer/explorer.go
Labels: bug-fix

#846 explorer/views: detect unsupported address types
  api/apiroutes.go
  db/dcrsqlite/apisource.go
  db/dcrsqlite/apisource_test.go
  explorer/explorer.go
  explorer/explorermiddleware.go
  explorer/explorerroutes.go
  explorer/explorertypes.go
  explorer/templates.go
  go.mod
  go.sum
  txhelpers/txhelpers.go
  txhelpers/txhelpers_test.go
  views/address.tmpl
  views/status.tmpl
Labels: work in progress

#866 [3.1] Get address for charts AJAX from stimulus dataset
  public/js/controllers/address.js
  views/address.tmpl
Labels: bug-fix

#850 Run npm install and run build in CI
  run_tests.sh
Labels: CI

#872 Move connection indicator & desktop notification logic out of index.js
  public/index.js
  public/js/controllers/connection_controller.js
  public/js/services/desktop_notification_service.js
  views/extras.tmpl
Labels: frontend

#862 Update to use dynamic database name. #414
  main.go
  sample-dcrdata.conf
Labels: enhancement

#873 Last of the inline JS removed
  public/index.js
  public/js/controllers/ticketwindow_controller.js
  views/extras.tmpl
  views/statistics.tmpl
  views/windows.tmpl
Labels: frontend

#881 [WIP] move nexthome logic out of index.js and into controllers
  public/index.js
  public/js/controllers/networkOverview_controller.js
  public/js/controllers/visualBlocks_controller.js
  public/js/services/desktop_notification_service.js
  public/js/services/event_bus_service.js
  views/nexthome.tmpl
Labels: ready to go

#891 [3.1.1] Change mempool last block age controller back to main
  views/mempool.tmpl
Labels: bug-fix

#886 [3.1.1] explorer: backport fix for possible panic on shutdown
  explorer/explorerroutes.go
Labels: backport, bug-fix

#845 Turbolinks-integrated query parameters and stimulus integration on address page
  api/apiroutes.go
  db/dbtypes/types.go
  db/dcrpg/chainmonitor.go
  db/dcrpg/insightapi.go
  db/dcrpg/pgblockchain.go
  db/dcrsqlite/apisource.go
  explorer/explorer.go
  explorer/explorerroutes.go
  explorer/explorertypes.go
  main.go
  public/js/controllers/address_controller.js
  public/js/helpers/chart_helper.js
  public/js/helpers/turbolinks_helper.js
  public/scss/address.scss
  public/scss/charts.scss
  rpcutils/rpcclient.go
  views/address.tmpl
  views/addresstable.tmpl
  views/extras.tmpl
Labels: enhancement, frontend

#883 dcrsqlite: mitigate database is locked errors
  db/dcrsqlite/sqlite.go
  explorer/explorermiddleware.go
Labels: backend, bug-fix
