Repository decred/dcrdata, pull requests merged in 2018-11, with the labels that each got.

#785 Header footer fixup
  public/css/bootstrap.css
  public/css/main.css
  public/css/nexthome.css
  public/images/logo_gradient_black.svg
  public/images/logo_white.svg
  views/extras.tmpl
Labels: UI / graphics, bug-fix

#779 Timebased blocks listing
  api/apiroutes.go
  db/dbtypes/conversion.go
  db/dbtypes/types.go
  db/dcrpg/internal/blockstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/queries.go
  db/dcrsqlite/apisource.go
  explorer/explorer.go
  explorer/explorerroutes.go
  explorer/explorertypes.go
  explorer/templates.go
  explorer/websockethandlers.go
  main.go
  public/css/main.css
  public/js/controllers/main.js
  public/js/controllers/status.js
  public/js/humanize.js
  views/explorer.tmpl
  views/extras.tmpl
  views/parameters.tmpl
  views/timelisting.tmpl
  views/windows.tmpl
Labels: UI / graphics, needs testing

#790 prevent footer text from jiggling when connection status changes
  public/css/main.css
  views/extras.tmpl
Labels: UI / graphics, bug-fix

#780 Block time counter in the footer
  db/dcrsqlite/apisource.go
  db/dcrsqlite/sqlite.go
  explorer/explorer.go
  explorer/explorerroutes.go
  explorer/explorertypes.go
  explorer/templates.go
  public/css/main.css
  public/js/controllers/main.js
  views/extras.tmpl
Labels: enhancement, needs testing

#777 Mempool transactions on /tx update (mostly) correctly now
  explorer/explorerroutes.go
  explorer/templates.go
  public/css/main.css
  views/extras.tmpl
  views/tx.tmpl
Labels: bug-fix

#795 Parameters page tweaks.
  explorer/explorerroutes.go
  explorer/explorertypes.go
  views/parameters.tmpl
Labels: bug-fix

#798 Disable buttons that plot a chart with one record.
  db/dbtypes/types.go
  db/dcrpg/internal/addrstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/queries.go
  explorer/explorer.go
  explorer/explorerroutes.go
  public/js/controllers/address.js
  views/address.tmpl
Labels: bug-fix

#789 upgrade to jquery v3.3.1
  public/js/controllers/charts.js
  public/js/controllers/mempool.js
  public/js/jquery-migrate.js
  public/js/jquery.js
  views/extras.tmpl
Labels: needs testing

#778 Elided text, vout/vin index, and table-layout: auto on tx page tables.
  explorer/explorerroutes.go
  explorer/explorertypes.go
  explorer/templates.go
  public/css/main.css
  public/css/nexthome.css
  views/extras.tmpl
  views/home.tmpl
  views/tx.tmpl
Labels: enhancement

#812 amount alignment fixes in chain state table
  public/css/main.css
  views/home.tmpl
Labels: UI / graphics, bug-fix

#811 css: trailing zeros should not have negative margin
  public/css/main.css
Labels: UI / graphics, bug-fix

#791 Set block time datatype to timestamp.
  api/apiroutes.go
  api/insight/apiroutes.go
  api/types/apitypes.go
  blockdata/blockdata.go
  cmd/scanblocks/scanblocks.go
  db/dbtypes/conversion.go
  db/dbtypes/extraction.go
  db/dbtypes/types.go
  db/dcrpg/internal/addrstmts.go
  db/dcrpg/internal/blockstmts.go
  db/dcrpg/internal/stakestmts.go
  db/dcrpg/internal/txstmts.go
  db/dcrpg/internal/vinoutstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/queries.go
  db/dcrpg/tables.go
  db/dcrpg/upgrades.go
  db/dcrsqlite/apisource.go
  db/dcrsqlite/sqlite.go
  db/dcrsqlite/sync.go
  explorer/explorer.go
  explorer/explorerroutes.go
  explorer/explorertypes.go
  explorer/mempool.go
  explorer/templates.go
  explorer/websockethandlers.go
  public/js/controllers/address.js
  public/js/controllers/agenda.js
  public/js/controllers/charts.js
  public/js/controllers/main.js
  public/js/controllers/ticketpool.js
  systemstesting/serverPerformanceTest.go
  views/address.tmpl
  views/block.tmpl
  views/explorer.tmpl
  views/extras.tmpl
  views/home.tmpl
  views/timelisting.tmpl
  views/tx.tmpl
  views/windows.tmpl
Labels: DB-upgrade

#817 Fix the group by chart buttons
  public/js/controllers/address.js
Labels: bug-fix

#819 dcrpg: pkScript addresses slice should be zero length when no addresses
  db/dcrpg/queries.go
Labels: bug-fix

#820 explorer: fix and test hashStart and hashEnd tmpl functions
  explorer/explorerroutes.go
  explorer/templates.go
  explorer/templates_test.go
Labels: bug-fix, needs review

#794 Extended search to check aux DB for blocks
  explorer/explorer.go
  explorer/explorermiddleware.go
  explorer/explorerroutes.go
Labels: enhancement

#816 pre-populate charts data tweaks
  explorer/explorer.go
Labels: bug-fix

#792 add a timeout context to the pg DB
  api/apiroutes.go
  api/insight/apiroutes.go
  api/insight/converter.go
  api/types/insightapitypes.go
  config.go
  config_test.go
  db/dbtypes/types.go
  db/dcrpg/insightapi.go
  db/dcrpg/internal/addrstmts.go
  db/dcrpg/internal/vinoutstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/queries.go
  db/dcrpg/sync.go
  db/dcrpg/upgrades.go
  explorer/explorer.go
  explorer/explorermiddleware.go
  explorer/explorerroutes.go
  explorer/explorertypes.go
  explorer/websockethandlers.go
  main.go
  public/js/controllers/address.js
Labels: enhancement

#828 Work with the new dcrd reorg ntfn sequence
  blockdata/chainmonitor.go
  db/dcrpg/chainmonitor.go
  db/dcrsqlite/apisource.go
  db/dcrsqlite/chainmonitor.go
  main.go
  notification/ntfnchans.go
  notification/ntfnhandlers.go
  rpcutils/rpcclient.go
  rpcutils/rpcclient_online_test.go
  stakedb/chainmonitor.go
  txhelpers/txhelpers.go
Labels: critical-fix

#830 [3.1] backport for dcrd RPC v5.0.0
  blockdata/chainmonitor.go
  db/dcrpg/chainmonitor.go
  db/dcrsqlite/apisource.go
  db/dcrsqlite/chainmonitor.go
  main.go
  notification/ntfnchans.go
  notification/ntfnhandlers.go
  rpcutils/rpcclient.go
  rpcutils/rpcclient_online_test.go
  stakedb/chainmonitor.go
  txhelpers/txhelpers.go
Labels: critical-fix

#808 Chainwork DB upgrade. Hashrate and Chainwork charts.
  cmd/rebuilddb2/rebuilddb2.go
  db/dbtypes/conversion.go
  db/dbtypes/types.go
  db/dcrpg/chainmonitor.go
  db/dcrpg/internal/blockstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/queries.go
  db/dcrpg/sync.go
  db/dcrpg/tables.go
  db/dcrpg/upgrades.go
  go.mod
  go.sum
  main.go
  public/js/controllers/charts_controller.js
  rpcutils/blockgate.go
  rpcutils/rpcclient.go
  views/charts.tmpl
Labels: DB-upgrade

#772 SQLite structure and routines updated for orphaned blocks
  api/apirouter.go
  api/apiroutes.go
  api/types/apitypes.go
  blockdata/blockdata.go
  blockmemdb.go
  db/dcrsqlite/apisource.go
  db/dcrsqlite/sqlite.go
  db/dcrsqlite/sync.go
  main.go
Labels: DB-upgrade, breaking-change, needs testing
