Repository decred/dcrdata, pull requests merged in 2018-09, with the labels that each got.

#659 explorer: address multiple deadlocks and data races
  explorer/explorer.go
  explorer/explorerroutes.go
  explorer/websockethandlers.go
Labels: critical-fix

#542 Current Ticket Pool Visualization
  api/apirouter.go
  api/apiroutes.go
  db/dbtypes/types.go
  db/dcrpg/internal/stakestmts.go
  db/dcrpg/internal/txstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/queries.go
  db/dcrpg/tables.go
  db/dcrpg/upgrades.go
  db/dcrsqlite/sync.go
  explorer/explorer.go
  explorer/explorerroutes.go
  explorer/websockethandlers.go
  main.go
  middleware/apimiddleware.go
  public/css/charts.css
  public/js/charts.min.js
  public/js/controllers/agenda.js
  public/js/controllers/ticketpool.js
  public/js/dygraph.min.js
  views/extras.tmpl
  views/ticketpool.tmpl
Labels: needs review, needs testing

#666 Transaction block list
  db/dcrpg/internal/txstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/queries.go
  explorer/explorer.go
  explorer/explorerroutes.go
  explorer/templates.go
  public/css/main.css
  views/tx.tmpl
Labels: enhancement

#668 dcrpg/dcrsqlite: no transactions found for address is not an error
  db/dcrpg/pgblockchain.go
  db/dcrsqlite/apisource.go
Labels: bug

#674 dcrpg: fix concurrent map write
  db/dcrpg/pgblockchain.go
Labels: critical-fix

#679 dcrpg: valid_mainchain addresses table patch
  db/dcrpg/internal/addrstmts.go
  db/dcrpg/internal/txstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/queries.go
  db/dcrpg/tables.go
  db/dcrpg/upgrades.go
Labels: bug

#686 insight: fix marshal of vout values in the tx message
  api/insight/socket.io.go
  api/insight/socket.io_test.go
Labels: bug, needs testing

#676 Invalidated transaction display
  db/dcrpg/internal/txstmts.go
  db/dcrpg/internal/vinoutstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/pgblockchain_test.go
  db/dcrpg/queries.go
  db/dcrsqlite/apisource.go
  explorer/explorer.go
  explorer/explorerroutes.go
  txhelpers/txhelpers.go
  views/tx.tmpl
Labels: work in progress

#688 [3.0] dcrpg: backported bugfixes
  db/dcrpg/internal/vinoutstmts.go
  db/dcrpg/pgblockchain_test.go
  db/dcrpg/queries.go
Labels: bug

#680 Show address page for address with ONLY unconfirmed Tx
  explorer/explorerroutes.go
  public/js/controllers/address.js
  views/address.tmpl
Labels: bug, needs review

#690 menu: remove duplicate "Block" item
  views/extras.tmpl
Labels: bug

#704 api: transaction output spent status
  api/apiroutes.go
  api/types/apitypes.go
Labels: enhancement, needs review

#706 dcrpg: addresses table query optimization with block_time_index sorting
  db/dcrpg/internal/addrstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/queries.go
  db/dcrpg/tables.go
  db/dcrpg/upgrades.go
Labels: enhancement

#707 rpcutils: initial ChainTips helper with tests
  go.mod
  go.sum
  rpcutils/rpcclient.go
  rpcutils/rpcclient_online_test.go
  rpcutils/rpcclient_test.go
Labels: enhancement

#660 Block visualization display at the newhome page
  db/dbtypes/conversion.go
  db/dcrsqlite/apisource.go
  db/dcrsqlite/sqlite.go
  explorer/explorer.go
  explorer/explorerroutes.go
  explorer/explorertypes.go
  explorer/templates.go
  main.go
  public/css/charts.css
  public/css/main.css
  public/css/nexthome.css
  public/images/abstain.svg
  public/images/block.svg
  public/images/connected.svg
  public/images/convert.svg
  public/images/copy-link.svg
  public/images/disconnected.svg
  public/images/general.svg
  public/images/logo-2018.svg
  public/images/menu.svg
  public/images/mining.svg
  public/images/search.svg
  public/images/staking.svg
  public/images/tickets.svg
  public/images/transactions.svg
  public/images/votes.svg
  public/images/wallet.svg
  public/js/humanize.js
  public/js/jquery.min.js
  views/address.tmpl
  views/agenda.tmpl
  views/agendas.tmpl
  views/block.tmpl
  views/charts.tmpl
  views/extras.tmpl
  views/home.tmpl
  views/mempool.tmpl
  views/nexthome.tmpl
  views/parameters.tmpl
  views/rawtx.tmpl
  views/sidechains.tmpl
  views/ticketpool.tmpl
  views/tx.tmpl
Labels: enhancement
