Repository decred/dcrdata, pull requests merged in 2019-04, with the labels that each got.

#1190 api: unexport apitypes.Status fields
  api/apiroutes.go
  api/insight/apiroutes.go
  api/types/apitypes.go
  main.go
  middleware/apimiddleware.go
  middleware/go.mod
Labels: backport-candidate

#1223 insight: fix "to" computation when not specified
  api/insight/apiroutes.go
  api/insight/apiroutes_test.go
Labels: bug-fix, insight API

#1236 rpcutils: fix a race in (*BlockPrefetchClient).GetBlockData
  rpcutils/prefetcher.go
Labels: bug-fix

#1235 dcrsqlite: verify the next block height
  db/dcrsqlite/go.mod
  db/dcrsqlite/go.sum
  db/dcrsqlite/sync.go
  go.mod
  go.sum
  rpcutils/blockgate.go
Labels: backport-candidate

#1265 dcrpg: update to v1.1.0 of github.com/lib/pg
  db/dcrpg/go.mod
  db/dcrpg/go.sum
  go.mod
  go.sum
  mempool/go.mod
  mempool/go.sum
Labels: needs testing

#1271 pstypes: SigNewTxs
  explorer/websocket.go
  explorer/websockethandlers.go
  go.mod
  public/js/controllers/homepage_controller.js
  public/js/controllers/mempool_controller.js
  pubsub/democlient/go.mod
  pubsub/democlient/go.sum
  pubsub/democlient/main.go
  pubsub/go.mod
  pubsub/go.sum
  pubsub/psclient/client.go
  pubsub/psclient/client_test.go
  pubsub/pubsubhub.go
  pubsub/types/pubsub_types.go
  pubsub/types/pubsub_types_test.go
  pubsub/websocket.go
Labels: breaking-change

#1292 dcrpg: meta table versioning
  cmd/rebuilddb2/rebuilddb2.go
  db/dcrpg/internal/meta.go
  db/dcrpg/internal/txstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/pgblockchain_charts_test.go
  db/dcrpg/pgblockchain_test.go
  db/dcrpg/queries.go
  db/dcrpg/rewind.go
  db/dcrpg/sync.go
  db/dcrpg/tables.go
  db/dcrpg/upgrades.go
  db/dcrpg/upgrades_legacy.go
  main.go
Labels: needs review

#1297 Update Release Status table in README for 4.0/4.1/5.0.
  README.md
Labels: backport-candidate
