Repository decred/dcrdata, pull requests merged in 2019-03, with the labels that each got.

#1053 caching and query tuning for InsightAddressTransactions
  db/dcrpg/insightapi.go
  db/dcrpg/internal/addrstmts.go
  db/dcrpg/internal/blockstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/queries.go
Labels: needs testing

#1077 dcrpg/cache: must store empty data as non-nil
  db/cache/addresscache.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/pgblockchain_test.go
Labels: bug-fix

#1083 wireddb/stakedb: proper synchronous ConnectBlock funcs
  blockdata/chainmonitor.go
  db/dcrsqlite/apisource.go
  main.go
  notification/ntfnchans.go
  stakedb/chainmonitor.go
Labels: bug-fix

#1116 explorer: create stub when address validates as other network
  db/dcrsqlite/apisource.go
Labels: backport-candidate, bug-fix

#1127 explorer: only signal mempool update once
  explorer/explorer.go
  public/js/services/messagesocket_service.js
  pubsub/pubsubhub.go
Labels: bug-fix

#1109 cache: rework address cache capacity
  api/insight/apiroutes.go
  cmd/rebuilddb2/rebuilddb2.go
  config.go
  db/cache/addresscache.go
  db/cache/log.go
  db/dbtypes/types.go
  db/dcrpg/insightapi.go
  db/dcrpg/insightapi_test.go
  db/dcrpg/internal/addrstmts.go
  db/dcrpg/log.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/pgblockchain_test.go
  db/dcrpg/queries.go
  explorer/explorerroutes.go
  main.go
  testutil/apiload/profiles.json
Labels: bug-fix, needs testing

#1129 tighten npm dep version specs
  package.json
Labels: bug-fix

#1121 explorer: refactor table CSS
  public/scss/responsive.scss
  public/scss/table.scss
  public/scss/themes.scss
  public/scss/typography.scss
  views/address.tmpl
  views/agenda.tmpl
  views/agendas.tmpl
  views/block.tmpl
  views/disapproved.tmpl
  views/explorer.tmpl
  views/extras.tmpl
  views/home.tmpl
  views/mempool.tmpl
  views/parameters.tmpl
  views/proposals.tmpl
  views/sidechains.tmpl
  views/timelisting.tmpl
  views/tx.tmpl
  views/windows.tmpl
Labels: needs testing

#1131 pubsub/types: Use net.Error
  dcrrates/rateserver/go.mod
  dcrrates/rateserver/go.sum
  pubsub/democlient/go.mod
  pubsub/democlient/go.sum
  pubsub/democlient/main.go
  pubsub/pubsubhub.go
  pubsub/types/pubsub_types.go
Labels: needs testing

#1139 Agendas: Drop RCI start height calculation
  db/dbtypes/types.go
  db/dcrpg/internal/stakestmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/queries.go
  db/dcrpg/upgrades.go
  explorer/explorer.go
  explorer/explorerroutes.go
  explorer/templates.go
  gov/agendas/deployments.go
  gov/agendas/deployments_test.go
  main.go
  public/js/controllers/address_controller.js
  public/js/controllers/agenda_controller.js
  public/js/controllers/charts_controller.js
  views/agenda.tmpl
  views/agendas.tmpl
  views/proposal.tmpl
Labels: bug-fix

#1186 db/cache: return a correctly-typed nil
  api/apiroutes.go
  blockdata/blockdata.go
  db/cache/addresscache.go
  db/cache/addresscache_test.go
  db/dbtypes/go.sum
  pubsub/pubsubhub.go
Labels: bug-fix

#1199 insight: block summary by time
  api/insight/apiroutes.go
  api/insight/apiroutes_test.go
  db/dbtypes/types.go
Labels: bug-fix, insight API

#1202 gov/politeia: Fix update for unauthorized proposals
  gov/politeia/proposals.go
Labels: backport-candidate, bug-fix

#1218 socket.io: check coinbase transaction addresses
  api/insight/socket.io.go
Labels: backport-candidate, bug-fix, insight API

#1217 socket.io test: update test html with address test
  api/insight/socket.io.slim.js
  api/insight/test_socket.html
  public/js/test_insight_socket.io.html
  public/js/vendor/socket.io.slim.js
  public/js/vendor/socket.io.slim.js.map
Labels: backport-candidate
