Repository decred/dcrdata, pull requests merged in 2019-05, with the labels that each got.

#1298 Insight root page and api redirect
  api/Insight_API_documentation.md
  api/insight/apirouter.go
  db/cache/charts.go
  explorer/explorer.go
  explorer/explorerroutes.go
  explorer/templates.go
  explorer/templates_test.go
  main.go
  middleware/apimiddleware.go
  sample-nginx.conf
  views/insight_root.tmpl
  views/ticketpool.tmpl
Labels: backport-candidate, insight API

#1305 db/cache: check input height in NewChartData
  db/cache/charts.go
  main.go
Labels: bug-fix

#1316 charts: Update derived data on db charts data query
  db/cache/charts.go
  db/cache/charts_test.go
Labels: backport-candidate

#1325 dcrpg: do not rollback dbtx on begin error
  db/dcrpg/pgblockchain.go
Labels: backport-candidate, bug-fix

#1329 node: update node-sass>node-gyp>tar dep
  package-lock.json
Labels: backport-candidate, bug-fix

#1322 [4.1] /api/status/happy and periodic node connection check
  api/apirouter.go
  api/apiroutes.go
  api/types/apitypes.go
Labels: backport

#1317 [4.1] insight: set limits on Insight addrs UTXOs and txns
  api/insight/apiroutes.go
  config.go
Labels: backport

#1321 API: /api/status/happy and periodic node peer connection check
  api/apirouter.go
  api/apiroutes.go
  api/types/apitypes.go
Labels: backport-candidate

#1352 Proposals: Change the reverse chronologically retrieval url parameter
  gov/politeia/proposals.go
Labels: backport-candidate

#1354 [4.1] Change the reverse chronologically sorting url to return new data
  go.mod
  go.sum
  gov/politeia/proposals.go
Labels: backport
