Repository decred/dcrdata, pull requests merged in 2019-07, with the labels that each got.

#1453 [5.0] charts: fix ticket pool value scale
  public/js/controllers/charts_controller.js
Labels: backport

#1466 api/types: do not omit zero-value InsightVin.Vout
  api/insight/converter.go
  api/types/insightapitypes.go
Labels: bug-fix

#1468 insight: DcrToInsightTxns can RPC for prevout addresses
  api/insight/converter.go
  db/dcrpg/insightapi.go
  db/dcrpg/queries.go
Labels: bug-fix

#1463 insight: add pageNum middleware and use in /txs endpoint
  api/insight/apirouter.go
  api/insight/apiroutes.go
  db/dcrpg/insightapi.go
  middleware/apimiddleware.go
Labels: bug-fix

#1470 insight: also check URL queries for params in PostAddrsTxsCtx middleware
  api/insight/apimiddleware.go
  api/insight/apiroutes.go
Labels: bug-fix

#1449 gov/politeia: Manage duplicate proposal ref id instances
  gov/politeia/proposals.go
  gov/politeia/proposals_test.go
  gov/politeia/types/types.go
Labels: bug-fix

#1476 dcrpg: AddressData should copy the cached AddressBalance
  db/cache/addresscache.go
  db/dcrpg/pgblockchain.go
Labels: bug-fix, critical-fix
