Repository decred/dcrdata, pull requests merged in 2019-06, with the labels that each got.

#1359 chart: Add purchased tickets axis to the ticket price chart
  db/cache/charts.go
  db/cache/charts_test.go
  db/dcrpg/internal/blockstmts.go
  db/dcrpg/queries.go
  public/js/controllers/charts_controller.js
  public/js/helpers/chart_helper.js
  public/scss/charts.scss
  views/charts.tmpl
  views/proposal.tmpl
Labels: frontend

#1294 CockroachDB support
  README.md
  cmd/rebuilddb2/rebuilddb2.go
  db/dcrpg/README.md
  db/dcrpg/indexing.go
  db/dcrpg/internal/addrstmts.go
  db/dcrpg/internal/blockstmts.go
  db/dcrpg/internal/common.go
  db/dcrpg/internal/meta.go
  db/dcrpg/internal/rewind.go
  db/dcrpg/internal/stakestmts.go
  db/dcrpg/internal/txstmts.go
  db/dcrpg/internal/vinoutstmts.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/pgblockchain_test.go
  db/dcrpg/queries.go
  db/dcrpg/rewind.go
  db/dcrpg/sync.go
  db/dcrpg/tables.go
  db/dcrpg/upgrades_legacy.go
  main.go
Labels: experimental

#1349 db/{cache,dcrpg}: improved memory management
  api/insight/apiroutes.go
  api/insight/apiroutes_test.go
  api/types/go.mod
  api/types/go.sum
  api/types/insightapitypes.go
  blockdata/go.mod
  db/cache/addresscache.go
  db/cache/addresscache_test.go
  db/cache/go.mod
  db/cache/go.sum
  db/dbtypes/types.go
  db/dcrpg/insightapi.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/queries.go
  dev/heap_in_use.m
Labels: backport-candidate

#1397 [4.1] disable multiple home page redirects after sync
  public/js/controllers/status_controller.js
Labels: backport

#1396 [4.1] update axios
  package-lock.json
  package.json
Labels: bug-fix, security-issue

#1395 [4.1] dcrpg/dbtypes: fix first uncached load of AddressHistory
  db/cache/addresscache.go
  db/dbtypes/types.go
  db/dcrpg/pgblockchain.go
  go.mod
Labels: bug-fix

#1384 cache/charts: check for genesis time 0
  db/cache/charts.go
  db/cache/charts_test.go
  db/dcrpg/pgblockchain_charts_test.go
  db/dcrsqlite/apisource_charts_test.go
  main.go
Labels: bug-fix

#1389 dcrpg: unconfirmed txs funding an address were not labeled funding
  db/dcrpg/pgblockchain.go
Labels: bug-fix

#1385 insight: socket.io tx event includes vins
  api/apiroutes.go
  api/insight/socket.io.go
  db/dcrsqlite/apisource.go
  explorer/websocket.go
  main.go
  mempool/monitor.go
  public/js/test_insight_socket.io.html
  pubsub/websocket.go
  txhelpers/txhelpers.go
Labels: insight API

#1394 dcrpg/dbtypes: fix first uncached load of AddressHistory
  db/cache/addresscache.go
  db/dbtypes/types.go
  db/dcrpg/pgblockchain.go
Labels: backport-candidate, bug-fix
