Repository decred/dcrdata, pull requests merged in 2019-01, with the labels that each got.

#916 Stylesheet cleanup
  .stylelintignore
  public/css/main.css
  public/scss/_variables.scss
  public/scss/_variables_reference.scss
  public/scss/application.scss
  public/scss/bootstrap_overrides.scss
  public/scss/charts.scss
  public/scss/global.scss
  public/scss/navigation.scss
  public/scss/transaction.scss
  views/home.tmpl
  views/statistics.tmpl
  views/tx.tmpl
Labels: work in progress

#918 dcrpg: Add block deletion/purge queries and functions.
  config.go
  db/dbtypes/types.go
  db/dcrpg/internal/blockstmts.go
  db/dcrpg/internal/rewind.go
  db/dcrpg/pgblockchain.go
  db/dcrpg/pgblockchain_test.go
  db/dcrpg/queries.go
  db/dcrpg/rewind.go
  db/dcrsqlite/sync.go
  main.go
  stakedb/stakedb.go
Labels: backend, enhancement

#922 dcrsqlite: Add purge block functions to WiredDB (sqlite)
  db/dcrpg/pgblockchain.go
  db/dcrpg/rewind.go
  db/dcrsqlite/apisource.go
  db/dcrsqlite/sqlite.go
  db/dcrsqlite/sync.go
  main.go
Labels: backend, enhancement

#925 dcrsqlite: have StoreBlock set existing blocks to side chain first
  db/dcrsqlite/chainmonitor.go
  db/dcrsqlite/sqlite.go
Labels: bug-fix

#929 middleware: fix incorrect ctxBlockIndex data type
  api/apirouter.go
  explorer/explorermiddleware.go
  middleware/apimiddleware.go
Labels: API, backport-candidate, bug-fix

#938 dcrpg: remove several unused columns from blocks table.
  db/dbtypes/conversion.go
  db/dbtypes/types.go
  db/dcrpg/internal/blockstmts.go
  db/dcrpg/queries.go
  db/dcrpg/tables.go
  db/dcrpg/upgrades.go
  db/dcrpg/upgrades_test.go
  explorer/syncstatus.go
Labels: DB-upgrade

#958 dcrpg/insight: fix get block summary by time
  api/insight/apiroutes.go
  db/dcrpg/queries.go
Labels: bug-fix, insight API

#953 new pubsub/psclient package and refactored mempool
  .gitignore
  README.md
  blockdata/chainmonitor.go
  config.go
  db/dcrsqlite/apisource.go
  explorer/explorerroutes.go
  explorer/mempool.go
  explorer/types/explorertypes.go
  explorer/types/explorertypes_test.go
  explorer/websockethandlers.go
  log.go
  main.go
  mempool/collector.go
  mempool/mempool.go
  mempool/mempoolcache.go
  mempool/monitor.go
  mempool/mptypes.go
  notification/ntfnchans.go
  notification/ntfnhandlers.go
  pubsub/democlient/config.go
  pubsub/democlient/go.mod
  pubsub/democlient/go.sum
  pubsub/democlient/main.go
  pubsub/log.go
  pubsub/psclient/client.go
  pubsub/psclient/client_test.go
  pubsub/pubsubhub.go
  pubsub/types/pubsub_types.go
  pubsub/websocket.go
  rpcutils/rpcclient.go
  sample-dcrdata.conf
  stakedb/chainmonitor.go
  websocket.go
Labels: enhancement, needs review, needs testing

#955 Attempt badger db recovery when the "truncate" error is encountered.
  stakedb/stakedb.go
  stakedb/ticketpool.go
Labels: backport-candidate, needs testing

#964 This fixes the bad checksum for Sereal.
  go.sum
  version/version.go
Labels: bug-fix

#921 Consolidate network overview design for /home [WIP]
  public/js/controllers/homepage_controller.js
  public/js/controllers/networkOverview_controller.js
  public/js/controllers/visualBlocks_controller.js
  public/js/helpers/humanize_helper.js
  public/scss/_variables.scss
  public/scss/global.scss
  public/scss/navigation.scss
  public/scss/nexthome.scss
  public/scss/themes.scss
  public/scss/typography.scss
  public/scss/utils.scss
  views/extras.tmpl
  views/home.tmpl
  views/nexthome.tmpl
Labels: UI / graphics, work in progress
